version: "3.8"
services:
  nodeserver:
    build:
      context: ./
    expose:
      - 8000
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - nodeserver
